"""empty message

Revision ID: 24c4d0f91c65
Revises: f75f87a5a620
Create Date: 2024-07-07 14:42:28.482071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c4d0f91c65'
down_revision = 'f75f87a5a620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_restaurant_pizzas_pizzas_restaurants', type_='foreignkey')
        batch_op.drop_constraint('fk_restaurant_pizzas_restaurants_pizzas', type_='foreignkey')
        batch_op.drop_column('pizzas')
        batch_op.drop_column('restaurants')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurants', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('pizzas', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_restaurant_pizzas_restaurants_pizzas', 'pizzas', ['restaurants'], ['id'])
        batch_op.create_foreign_key('fk_restaurant_pizzas_pizzas_restaurants', 'restaurants', ['pizzas'], ['id'])

    # ### end Alembic commands ###
