"""empty message

Revision ID: 4c77cfe1c00e
Revises: 24c4d0f91c65
Create Date: 2024-07-07 14:45:15.275674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c77cfe1c00e'
down_revision = '24c4d0f91c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pizzas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('restaurants', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_restaurant_pizzas_pizzas_pizzas'), 'pizzas', ['pizzas'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_restaurant_pizzas_restaurants_restaurants'), 'restaurants', ['restaurants'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_restaurant_pizzas_restaurants_restaurants'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_restaurant_pizzas_pizzas_pizzas'), type_='foreignkey')
        batch_op.drop_column('restaurants')
        batch_op.drop_column('pizzas')

    # ### end Alembic commands ###
