"""empty message

Revision ID: 81723667db9e
Revises: 1e0aecd03f5a
Create Date: 2024-07-07 14:32:49.675550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81723667db9e'
down_revision = '1e0aecd03f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pizzas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('restaurants', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_restaurant_pizzas_pizza_id_pizzas', type_='foreignkey')
        batch_op.drop_constraint('fk_restaurant_pizzas_restaurant_id_restaurants', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_restaurant_pizzas_restaurants_restaurants'), 'restaurants', ['restaurants'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_restaurant_pizzas_pizzas_pizzas'), 'pizzas', ['pizzas'], ['id'])
        batch_op.drop_column('pizza_id')
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('pizza_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_restaurant_pizzas_pizzas_pizzas'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_restaurant_pizzas_restaurants_restaurants'), type_='foreignkey')
        batch_op.create_foreign_key('fk_restaurant_pizzas_restaurant_id_restaurants', 'restaurants', ['restaurant_id'], ['id'])
        batch_op.create_foreign_key('fk_restaurant_pizzas_pizza_id_pizzas', 'pizzas', ['pizza_id'], ['id'])
        batch_op.drop_column('restaurants')
        batch_op.drop_column('pizzas')

    # ### end Alembic commands ###
